name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build-lint-test:
    strategy:
      matrix:
        os: [macos-latest]
        # As multi-platform support improves, I should add more operating systems here
        # os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check .
      - run: zig build
      - run: zig build test
